### ISSUE TITLE
knative service not found

### ISSUE THREAD

**Issue by Morriz** [redhat-developer/vscode-knative#167]
**Environment**
VS Code version: 1.63.2
OS: darwin
Extension version: 0.9.4
**Description**

We have a knative operator that installed a knative-serving component, and one ksvc is running, but nothing is reported as found by the extension. The eventing tab however, is showing some folders as if it is active, but we have no such component installed.

**Comment by mohitsuman** [comment]
@sudhirverma can you please test and update here this if it works with the latest extension code? We need to update the issue accordingly.

**Comment by sudhirverma** [comment]
@Morriz I have installed knative-serving component from the operator it is working fine for me. Can you check with latest version of Extension?

**Comment by Morriz** [comment]
I don't use it anymore as I don't seem to get value out of the extension, because I use k9s mostly for direct contact with resources. Anybody can test this tho

**Comment by mohitsuman** [comment]
Thanks for sharing the feedback @Morriz.
