### ISSUE TITLE
Functions: user should be notified about the result of an operation

### ISSUE THREAD

**Issue by zroubalik** [redhat-developer/vscode-knative#187]
If user runs Funciton -> Build/Deploy or similar operation, the terminal is being opened with the CLI output. As mentioned in #186 it is not ideal location. Also after the operation completes, the terminal tab remains opened, probably as bash session and not the default user shell (in my case I am using zsh). 
See the screenshot:
<img width="741" alt="terminal" src="https://user-images.githubusercontent.com/726523/157889057-d29421fb-d83b-4246-b0d3-7a5b531804db.png">

There should be a notification in the IDE UI, to notify that the Function has been successfuly built/deployed...or print error in case of a problem.

**Comment by sudhirverma** [comment]
I am running the build/deploy command on the terminal because for some image it can ask the user for a username and password it would be easy for the user to provide  username and password on the terminal.
 
<img width="830" alt="Screenshot 2022-03-20 at 8 29 19 PM" src="https://user-images.githubusercontent.com/9924513/159168965-163797f5-c22e-47ff-bbd5-2ecc3f4963c7.png">

**Comment by zroubalik** [comment]
But the result is many opened terminals in VScode, which is not nice from UX.

This prompt should be included in VS Code UI.

**Comment by mohitsuman** [comment]
@zroubalik is there a way to figure out if the image is private or not, when running the deploy command ?

**Comment by zroubalik** [comment]
@mohitsuman what do you mean by private?

**Comment by mohitsuman** [comment]
As @sudhirverma pointed out that the username/password prompt is needed in case of any primate image to be deployed. So wanted to know if func-cli can notify that it is an private image, we can prompt the user accordingly.

**Comment by zroubalik** [comment]
@matejvasek might help with that, he implemented the credentials provider in func, so might get an idea how to let vscode know that we will need prompt in advance.

**Comment by sudhirverma** [comment]
Fixed in #271

**Comment by mohitsuman** [comment]
With the latest release of the extension the workflow of the Run, Build and Deploy command will improve. In previous versions, for every command, there was a terminal tab opened up, which was not ideal to keep open after the operation ends.

With the new fix, the commands will run in `VSCode Output Channel` and the user is notified of the existing Run/Build/Deploy if any.

**Comment by zroubalik** [comment]
@mohitsuman awesome, great change! Thanks for this :)
