### ISSUE TITLE
Functions related view should be under Knative next to Serving and Eventing

### ISSUE THREAD

**Issue by zroubalik** [redhat-developer/vscode-knative#188]
<img width="230" alt="sidebar" src="https://user-images.githubusercontent.com/726523/157889634-322bbfe3-135a-4d41-98d5-3b2c9074f2f4.png">

There are two Knative related menu items in the VScode's sidebar, it should be merged into one to live next to Serving and Eventing.

**Comment by mohitsuman** [comment]
There should be just one Knative extension icon in the Sidebar. @sudhirverma can you have a look at the latest version and see if this issue persists.

**Comment by sudhirverma** [comment]
We had an agreement to create two Sidebar one for knative and the other for Functions.

cc. @jeffmaury @nainaz
