### ISSUE TITLE
Functions: icon for a namespace is confusing

### ISSUE THREAD

**Issue by zroubalik** [redhat-developer/vscode-knative#195]
A namespace icon in the Functions view is confusing, at the moment it is a Knative icon, but should be something more generic related to k8s.
<img width="395" alt="namespace" src="https://user-images.githubusercontent.com/726523/157896883-b76bbc09-8f8d-4f8f-a1a3-7c33e73939f2.png">
.

**Comment by mohitsuman** [comment]
@zroubalik can you recommend any icon to make sure we make it generic to K8s. Currently to represent the default workflow, we went ahead with the knative icon.

**Comment by zroubalik** [comment]
@mohitsuman unfortunately I am not sure. Funny thing is, that probably the current icon for Knative Service is more suitable at least from my POV 😄

Maybe we can use this as an inspiration: https://github.com/kubernetes/community/tree/master/icons 
But you are experts on this area.

@nainaz

**Comment by rhuss** [comment]
Why not the namespace icon from the Kubernetes catalog that @zroubalik referenced above ? The namespace concept is the same in knative as in kubernetes
