### ISSUE TITLE
Undeploy a function

### ISSUE THREAD

**Issue by mohitsuman** [redhat-developer/vscode-knative#291]
Add a command to undeploy a function.

### Undeploy the function defined in the local directory
func delete

### Undeploy the function 'myfunc' in namespace 'apps'
func delete -n apps myfunc

I see the code for `undeploy` is there but it is not reflected in package.json and on the context menu.

**Comment by sudhirverma** [comment]
@mohitsuman I have implemented the undeploy command. Is there something else you want me to do?

<img width="349" alt="Screenshot 2022-10-19 at 3 31 54 PM" src="https://user-images.githubusercontent.com/9924513/196661374-1c4660cf-da3e-4f18-980f-7edc6acb3275.png">

**Comment by mohitsuman** [comment]
<img width="402" alt="Screenshot 2022-10-19 at 4 25 33 PM" src="https://user-images.githubusercontent.com/3133356/196672610-d01d2ab3-eb2a-4dc6-8159-d51dff52dfa6.png">


Closing this as the undeploy action works.
