### ISSUE TITLE
Publish the vscode-knative extension to Open VSX

### ISSUE THREAD

**Issue by cgruver** [redhat-developer/vscode-knative#328]
This extension does not appear to be available from Open VSX, [https://open-vsx.org](https://open-vsx.org)

Due to the terms of use published on the Micorsoft marketplace, this extension is thus not available to users of open source builds of VS Code such as vscodium, or che-code included with Eclipse Che / OpenShift Dev Spaces.

Please consider publishing this extension to [https://open-vsx.org](https://open-vsx.org)

**Comment by mohitsuman** [comment]
Thanks for raising this @cgruver. We would publish the extension to open-vsx with the next release.

**Comment by cgruver** [comment]
Awesome!

Thanks.
