### ISSUE TITLE
Build failes with Error: unknown shorthand flag: 'n' in -n=default

### ISSUE THREAD

**Issue by tothandras** [redhat-developer/vscode-knative#335]
**Describe the bug**

```
------------------------------------------- Starting Build: hello -------------------------------------------

/root/.vs-func/func build -p=/workspaces/knative/hello -i=docker.io/tothandras/hello:latest -n=default -v
Error: unknown shorthand flag: 'n' in -n=default
'/root/.vs-func/func build -p=/workspaces/knative/hello -i=docker.io/tothandras/hello:latest -n=default -v' exited with code 1
```

**To Reproduce**
0. Extension installed kubectl, kn and func inside the dev container
1. Created a TypeScript http function with the extension
2. In the KNATIVE panel right click on the function and Build
3. Error is shown

**Comment by devav2** [comment]
+1

**Comment by mohitsuman** [comment]
Folks, we do not have any active contributor working on this repo currently. So if anyone wants to raise a PR, it is welcome. Meanwhile, we will try to make sure someone looks at it and fixes it.

Note: The latest functionality of Serverless Function (func CLI) is now moved to [VS Code OpenShift Toolkit](https://github.com/redhat-developer/vscode-openshift-tools) extension (actively developed).

**Comment by mohitsuman** [comment]
@tothandras @BDelacour We have made a new release for the extension which will have the fix for the mentioned issue. Please let us know if any other feedback.
