### ISSUE TITLE
Error: unknown shorthand flag: 'n' in -n=default

### ISSUE THREAD

**Issue by techpanga** [redhat-developer/vscode-knative#338]
**Environment**
VS Code version: 1.86.2
OS: darwin
Extension version: 1.4.0
**Description**

------------------------------------------- Starting Build: hello -------------------------------------------

/Users/xxxxx/.vs-func/func build -p=/Users/xxxxx/knative-code/hello -i=quay.io/xxxxxx/hello:latest -n=default -v
Error: unknown shorthand flag: 'n' in -n=default
'/Users/xxxxx/.vs-func/func build -p=/Users/xxxxx/knative-code/hello -i=quay.io/xxxxxx/hello:latest -n=default -v' exited with code 1

**Comment by mohitsuman** [comment]
Duplicate on #335
